### ISSUE TITLE
Menu Design and Creation

### ISSUE THREAD

**Issue by jwhittle933** [jwhittle933/UnderDevelopmentUI#15]
# Site Menu
* Design and Create `Menu` component 
* Determine functionality (site navigation, location, etc)

**Comment by jwosborn** [comment]
### Menu `li`'s

- Home
- Profile
- Authors
- About Us
- Contact
- Login

?? Additions/Subtractions?

**Comment by jwhittle933** [comment]
For the `Home` route, I think we should use the Logo in the middle of the header. So having a home nav option would be redundant, unless it becomes a problem. 

`Profile` is only relevant for users, which is a special class of site visitor. If we include it in the menu, it would need to be conditionally rendered based on logged in status. Or it could live in a special user menu on the right side of the header. 

`Authors` is good. 

`About Us` is good. 

`Contact` is fine, but we need to iron out exactly what goes here. 

`Login` will be handled by the user specific menu on the right side of the header. 

We need to determine how we want to handle `Subscriptions`, if its needs its own route and form, or if it's prominently displayed on certain pages. 

We should think through how to handle the `Posts` page. If the home page is a list of all posts, then we will only need to display a `Posts` option when you're not on that route. But perhaps the landing page should be prominent posts based on views, comments, etc., and have another `All Posts` route. 

I haven't written `tags` into any of the resources on the backend, but I think it's a good logical step. If we have options to search for resources (`Posts`) based on topic or tag, we may need to account for that in site navigation. 

Most importantly, we need to think hard about what this menu will look like, where will it live (always present or rendered on button click, etc.). A persistent menu takes up space, but a dynamic menu requires more logic. Maybe research some nice UI menus and steal some ideas.

**Comment by jwosborn** [comment]
#### A few thoughts: 

`Posts` and `Home` will essentially be the same as there is no reason the `Home` page wouldn't display latest posts. Instead, I think `Posts` has to be replaced with some sort of `Search` function that allows the user to pull up specific posts. `Tags` plays into that heavily. 

`Posts` can be an option within the `Author` view, of course, that displays latest posts by that `Author`. 

`Contact us` can easily go in the `Footer`. Will remove from `Menu`. 

`Login`: so essentially we'll have two `Menu`'s. A `NavMenu` and a `UserMenu` or something of the sort. No big deal. Just making sure to be clear. 

For now, I'm going to put the menu component on the left side of the page vertically. Subject to change. Glad you said something bc I was in the process of writing the logic for a hidden `menu` that unrolls from the `MenuIcon`. Would have wasted time.
